import { Booking } from "@/models/Booking";
import { Game } from "@/models/Game";
import { PricingRule } from "@/models/PricingRule";
import { AdditionalCharge } from "@/models/AdditionalCharge";
import { SessionEntry } from "@/models/SessionEntry";
import { Notification } from "@/models/Notification";

export async function processOvertimeAndExit(
  bookingId: string,
  exitedTime: Date,
  isForceEnd: boolean = false
) {
  const booking = await Booking.findById(bookingId);
  if (!booking) return { success: false, reason: "Booking not found" };

  const game = await Game.findById(booking.gameId).lean();
  if (!game) return { success: false, reason: "Game not found" };

  const minimumUnit = game.duration || 60;
  const maxUnits = (game.maximumDuration || 180) / minimumUnit;
  const maxBillableUnits = maxUnits + 1;
  const buffer = game.bufferMinutes || 0;

  const startedTime = new Date(booking.startTime as any);
  const actualDuration = Math.max(0, Math.floor((exitedTime.getTime() - startedTime.getTime()) / (60 * 1000)));

  const bookedDuration = Math.max(
    0,
    Math.floor((new Date(booking.endTime as any).getTime() - startedTime.getTime()) / (60 * 1000))
  );
  const bookedUnits = Math.ceil(bookedDuration / minimumUnit);

  let billableUnits = bookedUnits;
  if (actualDuration > bookedDuration + buffer) {
    billableUnits = Math.ceil((actualDuration - buffer) / minimumUnit);
  }
  billableUnits = Math.min(billableUnits, maxBillableUnits);

  const additionalUnits = Math.max(0, billableUnits - bookedUnits);

  // Update original booking
  booking.status = "COMPLETED";
  booking.exitedTime = exitedTime;
  if (isForceEnd) {
    booking.autoEnded = true;
  }
  await booking.save();

  // Handle company overtime entries vs non-company AdditionalCharge
  if (booking.playerType === "COMPANY") {
    // 1. Fetch related session entries for the company booking group
    const relatedEntries = await SessionEntry.find({
      bookingId: booking._id,
      softDeleted: false,
    });

    for (const entry of relatedEntries) {
      entry.status = "COMPLETED";
      entry.exitedTime = exitedTime;
      entry.actualDurationMinutes = actualDuration;
      entry.billableSessionUnits = billableUnits;
      await entry.save();

      // Create overtime child entries for this player
      if (additionalUnits > 0) {
        // Double check to make sure we don't duplicate overtime entries if already created
        const existingOvertimeCount = await SessionEntry.countDocuments({
          parentEntryId: entry._id,
          entryType: "OVERTIME",
          softDeleted: false,
        });

        if (existingOvertimeCount < additionalUnits) {
          for (let u = existingOvertimeCount + 1; u <= additionalUnits; u++) {
            const overStart = new Date(startedTime.getTime() + (bookedDuration + (u - 1) * minimumUnit) * 60 * 1000);
            const overEnd = new Date(overStart.getTime() + minimumUnit * 60 * 1000);

            await SessionEntry.create({
              bookingId: booking._id,
              bookingGroupId: entry.bookingGroupId,
              userType: entry.userType,
              userId: entry.userId,
              companyId: entry.companyId,
              companyEmployeeId: entry.companyEmployeeId,
              playerName: entry.playerName,
              mobile: entry.mobile,
              gameId: entry.gameId,
              gameName: entry.gameName,
              court: entry.court,
              startTime: overStart,
              endTime: overEnd,
              exitedTime: exitedTime,
              bookedDurationMinutes: minimumUnit,
              actualDurationMinutes: minimumUnit,
              billableSessionUnits: 1,
              status: "COMPLETED",
              entryType: "OVERTIME",
              parentEntryId: entry._id,
              overtimeUnitNumber: u,
              billableDurationMinutes: minimumUnit,
              autoGenerated: true,
            });
          }
        }
      }
    }
  } else {
    // 2. Non-company users AdditionalCharge (Auto deduct coins if booking utilized coins)
    if (additionalUnits > 0) {
      // Find PricingRule for minimum unit
      const count = booking.playersCount || 1;
      const rule = await PricingRule.findOne({
        gameId: booking.gameId,
        durationMinutes: minimumUnit,
        minPlayers: { $lte: count },
        maxPlayers: { $gte: count },
        active: true,
      }).lean();

      let priceForMinimumDuration = 0;
      if (rule) {
        if (rule.mode === "PER_PLAYER") {
          priceForMinimumDuration = count * rule.pricePerPlayer;
        } else {
          priceForMinimumDuration = rule.baseCourtPrice + count * rule.pricePerPlayer;
        }
      } else {
        const rateBasis = booking.price || booking.coinCost || 0;
        priceForMinimumDuration = Math.round((rateBasis / (bookedDuration || minimumUnit)) * minimumUnit);
      }

      const additionalAmount = priceForMinimumDuration * additionalUnits;

      if (additionalAmount > 0) {
        // Retrieve booking user
        const { User } = await import("@/models/User");
        const { Transaction } = await import("@/models/Transaction");
        const userObj = await User.findById(booking.userId);

        // Check if coin user (booking was made using coins or user has active coin balances)
        const isCoinBooking = booking.coinCost && booking.coinCost > 0;
        const hasCoinsAvailable = userObj && userObj.coinsAvailable !== undefined && userObj.coinsAvailable >= additionalAmount;

        if (isCoinBooking && userObj && hasCoinsAvailable) {
          // Auto-deduct coins directly
          userObj.coinsAvailable = (userObj.coinsAvailable || 0) - additionalAmount;
          userObj.coins = userObj.coinsAvailable;
          await userObj.save();

          // Create auto-settled additional charge
          await AdditionalCharge.create({
            userId: booking.userId,
            bookingId: booking._id,
            amount: additionalAmount,
            additionalUnits,
            reason: `OVERTIME (COIN DEDUCTION): played ${actualDuration} minutes (booked ${bookedDuration} minutes) for ${count} player(s). Extra: ${additionalUnits} unit(s).`,
            status: "PAID",
            gatewayPaymentStatus: "PAID",
            adminPaymentStatus: "PAID",
            effectivePaymentStatus: "PAID",
          });

          // Log transaction
          await Transaction.create({
            userId: booking.userId,
            type: "SESSION_DEDUCTION",
            amount: 0,
            coins: additionalAmount,
            note: `Auto-charged overtime for ${booking.gameName} (Booking ID: ${booking._id})`,
            paymentMode: "coins",
            paymentStatus: "PAID",
          });

          await Notification.create({
            userId: booking.userId,
            title: "Overtime Charged",
            message: `Your session for ${booking.gameName} exceeded scheduled limit. ${additionalAmount} coins have been auto-deducted for ${additionalUnits} overtime unit(s).`,
            type: "SESSION_OVERTIME",
            clearable: true,
            cleared: false,
            relatedEntityType: "Booking",
            relatedEntityId: booking._id,
          });
        } else {
          // Standard cash/pending charge creation (for cash players, or if coin user has insufficient coins)
          await AdditionalCharge.create({
            userId: booking.userId,
            bookingId: booking._id,
            amount: additionalAmount,
            additionalUnits,
            reason: `OVERTIME: played ${actualDuration} minutes (booked ${bookedDuration} minutes) for ${count} player(s). Extra: ${additionalUnits} unit(s) based on rule calculation.`,
            status: "PENDING",
            gatewayPaymentStatus: "PENDING",
            adminPaymentStatus: "PENDING",
            effectivePaymentStatus: "PENDING",
            requestedByAdmin: false,
          });

          await Notification.create({
            userId: booking.userId,
            title: "Session Overtime Charge",
            message: `Your session for ${booking.gameName} has been completed. An overtime charge of ₹${additionalAmount} has been registered for the extra playtime and is awaiting admin review.`,
            type: "SESSION_OVERTIME",
            clearable: true,
            cleared: false,
            relatedEntityType: "Booking",
            relatedEntityId: booking._id,
          });
        }
      }
    }
  }

  return {
    success: true,
    actualDuration,
    bookedDuration,
    billableUnits,
    additionalUnits,
  };
}
