import { SessionEntry } from "@/models/SessionEntry";
import { CompanyBill } from "@/models/CompanyBill";
import { Game } from "@/models/Game";
import { AdminAuditLog } from "@/models/AdminAuditLog";

export async function recalculateCompanyBilling(
  companyId: string,
  gameId: string,
  oldMinDuration: number,
  newMinDuration: number,
  adminId: string
): Promise<number> {
  // 1. Retrieve all billed session entry IDs (non-cancelled bills)
  const billedBills = await CompanyBill.find({
    companyId,
    status: { $ne: "CANCELLED" },
    softDeleted: false,
  }).select("items.sessionEntryId").lean();

  const billedEntryIds = new Set(
    billedBills.flatMap((bill: any) =>
      (bill.items || []).map((item: any) => item.sessionEntryId?.toString())
    ).filter(Boolean)
  );

  // 2. Fetch the game to check maximum duration and buffer minutes
  const game = await Game.findById(gameId).lean();
  if (!game) throw new Error("Game not found");

  const buffer = game.bufferMinutes || 0;
  const maxLimit = game.maximumDuration || 180;

  // 3. Query all unbilled regular session entries for this company and game
  const unbilledEntries = await SessionEntry.find({
    companyId,
    gameId,
    entryType: "REGULAR",
    softDeleted: false,
  });

  const targetEntries = unbilledEntries.filter(
    (entry) => !billedEntryIds.has(entry._id.toString())
  );

  let updatedCount = 0;

  for (const entry of targetEntries) {
    const bookedDuration = entry.bookedDurationMinutes || 60;
    const bookedUnits = Math.ceil(bookedDuration / newMinDuration);

    if (entry.status === "COMPLETED" && entry.exitedTime) {
      const actualDuration = entry.actualDurationMinutes || Math.max(
        0,
        Math.floor((new Date(entry.exitedTime).getTime() - new Date(entry.startTime).getTime()) / 60000)
      );

      let billableUnits = bookedUnits;
      if (actualDuration > bookedDuration + buffer) {
        billableUnits = Math.ceil((actualDuration - buffer) / newMinDuration);
      }

      const maxUnits = maxLimit / newMinDuration;
      const maxBillableUnits = maxUnits + 1;
      billableUnits = Math.min(billableUnits, maxBillableUnits);

      entry.billableSessionUnits = billableUnits;
      await entry.save();

      // Recalculate and re-create child overtime entries
      await SessionEntry.deleteMany({
        parentEntryId: entry._id,
        entryType: "OVERTIME",
      });

      const additionalUnits = Math.max(0, billableUnits - bookedUnits);
      for (let u = 1; u <= additionalUnits; u++) {
        const overStart = new Date(new Date(entry.startTime).getTime() + (bookedDuration + (u - 1) * newMinDuration) * 60 * 1000);
        const overEnd = new Date(overStart.getTime() + newMinDuration * 60 * 1000);

        await SessionEntry.create({
          bookingId: entry.bookingId,
          bookingGroupId: entry.bookingGroupId,
          userType: entry.userType,
          userId: entry.userId,
          companyId: entry.companyId,
          companyEmployeeId: entry.companyEmployeeId,
          playerName: entry.playerName,
          mobile: entry.mobile,
          gameId: entry.gameId,
          gameName: entry.gameName,
          court: entry.court,
          startTime: overStart,
          endTime: overEnd,
          exitedTime: entry.exitedTime,
          bookedDurationMinutes: newMinDuration,
          actualDurationMinutes: newMinDuration,
          billableSessionUnits: 1,
          status: "COMPLETED",
          entryType: "OVERTIME",
          parentEntryId: entry._id,
          overtimeUnitNumber: u,
          billableDurationMinutes: newMinDuration,
          autoGenerated: true,
        });
      }
    } else {
      // Uncompleted entries (BOOKED/STARTED)
      entry.billableSessionUnits = bookedUnits;
      await entry.save();
    }

    updatedCount++;
  }

  // 4. Log the audit entry to AdminAuditLog
  const mongoose = require("mongoose");
  const isValidAdminId = mongoose.Types.ObjectId.isValid(adminId);
  const logAdminId = isValidAdminId 
    ? adminId 
    : (await mongoose.model("User").findOne({ role: "ADMIN" }).select("_id").lean())?._id;

  if (logAdminId) {
    await AdminAuditLog.create({
      action: "RECALCULATE_COMPANY_BILLING",
      adminId: logAdminId,
      targetUserId: logAdminId,
      reason: "Company Minimum Duration configuration changed",
      details: {
        companyId: companyId.toString(),
        gameId: gameId.toString(),
        oldMinimumDuration: oldMinDuration.toString(),
        newMinimumDuration: newMinDuration.toString(),
        existingEntriesUpdated: "YES",
        entriesUpdated: updatedCount.toString(),
        updatedBy: isValidAdminId ? "ADMIN" : "SYSTEM",
      },
    });
  }

  return updatedCount;
}
