import mongoose, { Schema, models } from "mongoose";

const SessionEntrySchema = new Schema(
  {
    bookingId: { type: Schema.Types.ObjectId, ref: "Booking" },
    bookingGroupId: { type: String, required: true },
    userType: {
      type: String,
      enum: ["PLAYER", "VISITOR", "COMPANY_EMPLOYEE"],
      required: true,
    },
    userId: { type: Schema.Types.ObjectId, ref: "User" },
    companyId: { type: Schema.Types.ObjectId, ref: "Company" },
    companyEmployeeId: { type: Schema.Types.ObjectId, ref: "CompanyEmployee" },
    playerName: { type: String, required: true },
    mobile: { type: String, required: true },
    gameId: { type: Schema.Types.ObjectId, ref: "Game", required: true },
    gameName: { type: String, required: true },
    court: { type: String, required: true },
    startTime: { type: Date, required: true },
    endTime: { type: Date, required: true },
    exitedTime: { type: Date },
    bookedDurationMinutes: { type: Number, required: true },
    actualDurationMinutes: { type: Number },
    billableSessionUnits: { type: Number },
    status: {
      type: String,
      enum: ["BOOKED", "STARTED", "COMPLETED", "CANCELLED"],
      default: "BOOKED",
    },
    softDeleted: { type: Boolean, default: false },
    createdBy: { type: Schema.Types.ObjectId },
    entryType: {
      type: String,
      enum: ["REGULAR", "OVERTIME"],
      default: "REGULAR",
    },
    parentEntryId: { type: Schema.Types.ObjectId, ref: "SessionEntry" },
    overtimeUnitNumber: { type: Number },
    billableDurationMinutes: { type: Number },
    autoGenerated: { type: Boolean, default: false },
    companyOvertimeStatus: {
      type: String,
      enum: ["PENDING", "REVIEWED", "INCLUDED"],
      default: "PENDING",
    },
  },
  { timestamps: true }
);

SessionEntrySchema.index({ bookingId: 1 });
SessionEntrySchema.index({ status: 1, startTime: 1, softDeleted: 1 });
SessionEntrySchema.index({ userId: 1, status: 1 });
SessionEntrySchema.index({ gameId: 1, status: 1 });
SessionEntrySchema.index({ entryType: 1, status: 1 });
SessionEntrySchema.index({ companyId: 1, gameId: 1, entryType: 1 });
SessionEntrySchema.index({ parentEntryId: 1 });

export const SessionEntry = models.SessionEntry || mongoose.model("SessionEntry", SessionEntrySchema);
